[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.2"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.104"
web-sys = { version = "0.3", features = ["Document", "Window", "Element"] }
console_error_panic_hook = "0.1"